### ISSUE TITLE
Issue while building apk for android

### ISSUE THREAD

**Issue by Rishan99** [mafreud/gallery_saver_plus#6]
Android resource linking failed
     ERROR: /Users/aria/Desktop/Personal/uno-user-app/build/gallery_saver_plus/intermediates/merged_res/release/values/values.xml:211: AAPT: error: resource android:attr/lStar not found.

**Comment by Rishan99** [comment]
Update: https://github.com/mafreud/gallery_saver_plus/pull/5

**Comment by mafreud** [comment]
@Rishan99 i will check it out ASAP. Thanks!

**Comment by Rishan99** [comment]
@mafreud  I have created a PR

**Comment by mafreud** [comment]
@Rishan99 Thank you for the issue and PR. Just published 3.2.1. https://pub.dev/packages/gallery_saver_plus/changelog
